server:
#  配置端口号
  port: 8001

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/project?userUnicode=true&characterEncoding=utf-8&useSSL=false&serverTImezone=UTC
    driverClassName: com.mysql.jdbc.Driver

#配置mapper文件
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
